name: api-rpc-pegnet
version: '0.1.1.2'
category: Web
author: Sergey Bushnyak
maintainer: sergey.bushnyak@sigrlami.eu
synopsis: simple json-rpc client for PegNet
description: simple json-rpc client for PegNet integration
copyright: ! 'Copyright: (c) 2019 Sergey Bushnyak'
license: MIT
github: sigrlami/api-rpc-pegnet
extra-source-files:
- README.md
dependencies:
  - base >=4.7 && <5
  - aeson
  - aeson-casing
  - text
  - time
  - http-conduit
  - http-client
  - http-client-tls
  - network
  - transformers
  - remote-monad
  - remote-json
  - remote-json-client
  # - json-autotype
  - json-alt
  - bytestring
library:
  source-dirs: src
  exposed-modules:
  - PegNet.RPC.Api
  - PegNet.RPC.Types.Balances
  - PegNet.RPC.Types.Issuance
  - PegNet.RPC.Types.Rates
  - PegNet.RPC.Types.RichEntry
  - PegNet.RPC.Types.SyncStatus
  - PegNet.RPC.Types.Transaction
  - PegNet.RPC.Types.TransactionStatus
tests:
  factom-test:
    main: Spec.hs
    source-dirs: tests
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - api-rpc-pegnet
