resolver: lts-14.0

allow-newer: true

packages:
- .

extra-deps:
- git: 'https://github.com/sigrlami/remote-json'
  commit: '3db7446c1451cd97aa22b424deb9ce9c25259a36'
  subdirs:
    - .
    - remote-json-client
- git: 'https://github.com/ku-fpg/remote-monad'
  commit: '79d22ea2bde876e6640a25472d90fc3d7dd82a3a'
